services:
  base_chat:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_ROUTE_ROOT={"method":"GET","url":"/","controller":"rootController"}
      - SERVER_ROUTE_ROOT2={"method":"GET","url":"/2","controller":"root2Controller"}
      - SERVER_ROUTE_ROOT3=qqq
      - SERVER_ROUTE_ROOT4=sadsdasdas
      - SERVER_SOCKET_IO=chatController
  chat1:
    extends:
      service: base_chat
    ports:
      - 3001:3000
  chat2:
    extends:
      service: base_chat
    ports:
      - 3002:3000
  chat3:
    extends:
      service: base_chat
    ports:
      - 3003:3000
  chat4:
    extends:
      service: base_chat
    ports:
      - 3004:3000
  chat5:
    extends:
      service: base_chat
    ports:
      - 3005:3000
  chat6:
    extends:
      service: base_chat
    ports:
      - 3006:3000
  chat7:
    extends:
      service: base_chat
    ports:
      - 3007:3000
  nginx:
    image: nginx:1.27.2-alpine-slim
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
