version: '3.8'
services:
  chat-client:
    build:
      context: dist/apps/chat-client
      dockerfile: Dockerfile
    ports:
      - '80:80'
  api-gateway:
    build:
      context: dist/apps/api-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:3000
