services:
  base_accounts:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_TYPE=http
      - SERVER_ROUTE_ROOT={"method":"GET","url":"/","controller":"rootController"}
      - SERVER_SOCKET_IO={"controller":"socketIOController"}
  accounts1:
    extends:
      service: base_accounts
    ports:
      - 4001:3000
