# Ports
# Load balancer           = 3001
# Microservice instance 1 = 30011
# Microservice instance 2 = 30012
# Microservice instance 3 = 30013
# Microservice instance 4 = 30014
# Microservice instance 5 = 30015
# Database                = 30010

services:
  # base
  base_accounts:
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: base_accounts
    environment:
      - SERVER_TYPE=http
      - HTTP_ROUTE_SIGN_IN={"method":"POST","url":"/sign-in","controller":"signInController"}
      - HTTP_ROUTE_SIGN_UP={"method":"POST","url":"/sign-up","controller":"signUpController"}
      - HTTP_ROUTE_PROTECTED={"method":"POST","url":"/protected","controller":"protectedController"}
      - HTTP_ROUTE_LOGOUT={"method":"POST","url":"/logout","controller":"logoutController"}
      - HTTP_ROUTE_FETCH_ACCOUNT={"method":"POST","url":"/fetch-account","controller":"fetchAccountController"}
      - MYSQL_HOST=accounts_db
      - MYSQL_DATABASE=accounts
      - MYSQL_PORT=30010
      - MYSQL_CORS=*
    depends_on:
      - accounts_db
  # load balancer
  accounts_load-balancer:
    image: nginx:stable-alpine-perl
    container_name: accounts_load-balancer
    ports:
      - 3001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - base_accounts
  # microservice instances
  accounts1:
    extends:
      service: base_accounts
    container_name: accounts1
    ports:
      - 30011:3000
  accounts2:
    extends:
      service: base_accounts
    container_name: accounts2
    ports:
      - 30012:3000
  accounts3:
    extends:
      service: base_accounts
    container_name: accounts3
    ports:
      - 30013:3000
  accounts4:
    extends:
      service: base_accounts
    container_name: accounts4
    ports:
      - 30014:3000
  accounts5:
    extends:
      service: base_accounts
    container_name: accounts5
    ports:
      - 30015:3000
  # database
  accounts_db:
    image: mysql:8.4
    container_name: accounts_db
    ports:
      - 30010:30010
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_TCP_PORT: 30010
    volumes:
      - accounts_db_volumes:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  accounts_db_volumes:
    driver: local
