services:
  base_accounts:
    build:
      context: ./
      dockerfile: Dockerfile.node
    environment:
      - SERVER_TYPE=http
      - HTTP_ROUTE_ROOT={"method":"GET","url":"/","controller":"rootController"}
  accounts1:
    extends:
      service: base_accounts
    ports:
      - 4001:3000
