services:
  accounts_db:
    image: mysql:9.1
    container_name: accounts_db
    ports:
      - 5001:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: accounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - accounts_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  accounts:
    build:
      context: ./
      dockerfile: Dockerfile.node
    container_name: accounts
    ports:
      - 4001:3000
    environment:
      - SERVER_TYPE=http
      - HTTP_ROUTE_ROOT={"method":"POST","url":"/","controller":"rootController"}
      - MYSQL_HOST=accounts_db
      - MYSQL_DATABASE=accounts
    depends_on:
      - accounts_db
volumes:
  accounts_db_data:
    driver: local
