CREATE TABLE IF NOT EXISTS accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nick VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS blockedTokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(10000) NOT NULL
);
