services:
  chat1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - SERVER_PORT=3001
  chat2:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - SERVER_PORT=3002
  chat3:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    environment:
      - SERVER_PORT=3003
  chat4:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3004:3004
    environment:
      - SERVER_PORT=3004
  chat5:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    environment:
      - SERVER_PORT=3005
  nginx:
    image: nginx:latest
    ports:
      - 3006:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
