services:
  base_chat:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_ROUTE_GET_ROOT={"method":"GET","url":"/","controller":"getRootController"}
  chat1:
    extends:
      service: base_chat
    ports:
      - 3001:3000
    environment:
      - SERVER_PORT=3001
  chat2:
    extends:
      service: base_chat
    ports:
      - 3002:3000
    environment:
      - SERVER_PORT=3002
  chat3:
    extends:
      service: base_chat
    ports:
      - 3003:3000
    environment:
      - SERVER_PORT=3003
  chat4:
    extends:
      service: base_chat
    ports:
      - 3004:3000
    environment:
      - SERVER_PORT=3004
  chat5:
    extends:
      service: base_chat
    ports:
      - 3005:3000
    environment:
      - SERVER_PORT=3004
  chat6:
    extends:
      service: base_chat
    ports:
      - 3006:3000
    environment:
      - SERVER_PORT=3006
  chat7:
    extends:
      service: base_chat
    ports:
      - 3007:3000
    environment:
      - SERVER_PORT=3007
  nginx:
    image: nginx:1.27.2-alpine-slim
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
